### ISSUE TITLE
Does not reject on status codes !== 200

### ISSUE THREAD

**Issue by ConnorLanglois** [PatNeedham/google-it#35] opened 2020-01-15 04:13 UTC
**Version of google-it**
1.4.2

**Versions of npm and node**
npm: 6.13.4
node: 11.6.0

**Describe the bug**
Use: As an imported package (i.e. not command line)

The main function googleIt does not throw errors when the response from google has status code !== 200. Instead, it returns an empty array. This is because the function googleIt uses the function getResponseBody, but getResponseBody does not throw an error when this occurs. I believe this is due to the way the "request" library works, in that the request library does not set the error parameter in the callback.

**Expected behavior**
To be able to catch errors where status code !== 200, it would be better to check the status code and reject accordingly. For example, in the callback of the request call of getResponseBody:

```
if (response.statusCode !== 200) {
    reject(response);
}
```

This way, with a response code like 429 "Too Many Requests", receiving the response in the catch handler would allow for logging and reporting.

I am not sure what effects this change would have on other code in the library and in dependants. It could be a breaking change.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by PatNeedham** [comment] 2020-01-16 18:50
Thank you for bringing this up @ConnorLanglois . I remember [removing that 200 status code check](https://github.com/PatNeedham/google-it/commit/8b9038b8d5a8e09c883bf047450c66858ceb4809#diff-eb698ef886ad12edc1d6636aef7041ef) as it was responsible for too many false positives, but unfortunately I didn't include any example of that (or reference to one) as part of the commit message! I will investigate this later today/tomorrow.

There should be a way to still attempt to perform that response parsing even if the status code isn't 200. My current thoughts are to change `getResponseBody` to just `getResponse` so it returns both the response body and status code (and possibly other relevant stuff). I think the only time it should throw an error is if there's no response body at all.

**Comment by ConnorLanglois** [comment] 2020-01-16 20:01
Absolutely! Interesting about the false positives, any examples you know of where this occurs? Does Google sometimes return valid search results with a non-200 code, sparking a false positive?

As per your comment about throwing an error only if there is no response body, I happen to need the response body when a 429 occurs, if possible. Here, Google returns a reCAPTCHA check for the user to check off. So, my use case is to receive the HTML of the page when a 429 occurs and to handle the reCAPTCHA myself. But, if you're saying false positives occur where Google returns non-200 codes for valid search results, this might not be possible. Maybe Google returns only a select few codes, including 200, for valid results? I doubt they would send 429 with valid results but I could be wrong!

In any case, I'm very interested in what you find!

**Comment by PatNeedham** [comment] 2020-01-19 04:24
So I looked into it can can confirm getting the 429 status code response,  with the `Our systems have detected unusual traffic from your computer network.` in the returned HTML page.

I'm leaning against having
```
if (response.statusCode !== 200) {
    reject(response);
}
```
as expected behavior, mainly due to the large size of that response object. Because if someone were to use this via the CLI, that object would become a giant wall of text confusing those who might not know what caused it to appear. What do you think if there were a `diagnostics` option which, if included, made the googleIt function resolve with that raw response instead of erroring out? Something like:
```
if (results.length === 0 && statusCode !== 200 && !diagnostics) {
        reject(new Error(`Error in response: statusCode ${statusCode}. To see the raw response object, please include 'diagnostics: true' as part of the options object (or -d if using command line)`));
}
```

**Comment by PatNeedham** [comment] 2020-01-19 04:38
Forgot to answer your question about the non-200 status code false positive. I can't tell for sure but if I had to guess I'd say [206 Partial content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206) status code might have been returned. With that `diagnostics` option it would be easier to find out when looping through responses, as it would just require printing / saving the non-200 responses that still yielded search results.

**Comment by ConnorLanglois** [comment] 2020-01-20 02:42
Ok sounds good to me! `diagnostics` options sound like the way to go.

**Comment by PatNeedham** [comment] 2020-01-24 03:06
My bad, this was closed prematurely. 1) I only want to close it once the version that addresses this is available on npm 2) I botched the PR I made by accidentally making the edits in the `lib` folder for option definitions instead of doing it in `src` then running `npm run build`. I need to automate those parts, but that's an issue for another day! I'll get to the npm release shortly.

**Comment by PatNeedham** [comment] 2020-01-24 03:22
v1.4.3 is now available.

This example:
```
const googleIt = require('google-it');

googleIt({ query: 'first google search I can think of', diagnostics: true })
  .then(({ results, response }) => {
    console.log('results.length: ' + results.length);
    console.dir(response);
  })
  .catch(error => console.log('something bad happened'));
```
Leads to this output:
![image](https://user-images.githubusercontent.com/967811/73042282-a5d77500-3e2e-11ea-96e8-dea7766825ac.png)

and further down:
![image](https://user-images.githubusercontent.com/967811/73042301-bc7dcc00-3e2e-11ea-8756-503e7bad2a4e.png)

I think in v2 of this library I'll set the `noDisplay` option to default to true when it's run programmatically.

**Closed** 2020-01-24 03:26 UTC
